---
name: Build Docker Image

on: [ workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert repository name to lowercase
        id: repo-name-lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:0.0.${{ github.run_number }}, ghcr.io/${{ env.REPO_NAME }}:latest
          build-args: BUILD_APP_VERSION=0.0.${{ github.run_number }}